#!/bin/bash

set -ex # o pipefail

_borg=(borg)

if [ -n "$SSH_PASS" ]; then
  _borg=(sshpass -p "$SSH_PASS" "${_borg[@]}")
fi

if [ -n "$SET_CWD" ]; then
  cd "$SET_CWD"
fi

#if [ -n "$YES_PIPE" ]; then
#  yes | "${_borg[@]}" "$@"
#else
#  "${_borg[@]}" "$@"
#fi

yes | "${_borg[@]}" "$@"
